version: '3.8'
services:
  stable-diffusion:
    image: stable-diffusion
    volumes:
      - .:/app  # Mount the current directory as /app in the container
      - ./data:/app/data  # Mount the data directory for inputs/outputs
    command: python /app/scripts/txt2img.py --prompt "A futuristic cityscape" --output_dir /app/data/output
